language: java

services:
  - mysql

before_install:
  - mysql -u root < ./events_registry.sql

script: mvn clean compile package
   
notifications:
  email:
    - angelocaporaso03@gmail.com
    - upcovino@gmail.com
  on_success: change
  on_failure: always
